takashi365/freemarket_sample_61d

README.md

test_hirota1

---

app/controllers/items_controller.rb
app/views/items/index.html.erb
config/application.rb
config/routes.rb

マークアップ 実装用

---

config/deploy.rb
config/environments/production.rb

- config.assets.js_compressor = uglifier　を削除（uglifireは使わないため）

production.rbの変更

---

config/routes.rb

bundle install
rails db:create
indexのルーティング修正
ビューを表示させるため

indexルーティング修正

---

app/controllers/signup_controller.rb
app/views/signup/step1.html.haml
config/routes.rb

- signup_controllerの作成
- ルーティングの設定
- ビューの記述（hamlでheaderのみ）
- ウィザード形式フォームで新規登録をする
- SCSSファイルの更新があった為、一度同期する

Signup add

---

Gemfile
Gemfile.lock

- recaptcha
- dotenv
- active_hash

必要な gemのインストール

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/profile.scss
app/controllers/users_controller.rb
app/views/users/_mypage-side.html.haml
app/views/users/edit.html.haml

プロフィール画面のマークアップをしました。
edit.html.hamlに記載しページが遷移できるようにしました。

　プロフィール画面の実装

---

app/assets/stylesheets/_registration.scss
app/views/signup/entry_start.html.haml
app/views/signup/member_infomation.html.haml
app/views/signup/phone_number.html.haml
app/views/signup/sms_check.html.haml

- サインアップの方法を選択するページをサインアップ
- font-awe-someでアイコンを実装
- 実際のログイン機能は未実装
- ログイン方法をユーザーが選択できるページを作成する為
https://gyazo.com/c573abdc86c2b81e0a4cee7756c1a176

Entry start

---

app/assets/stylesheets/mypage-side.scss
app/assets/stylesheets/mypage.scss
app/controllers/users_controller.rb
app/views/users/_mypage-side.html.haml
app/views/users/notification.html.haml
config/routes.rb

お知らせからお知らせページに遷移するようにしました。
お知らせページのマークアップをしました。
HTMLとCSSの記述をしました。
マイページと同じ内容だったので流用しました。
マイページのお知らせ部分のCSSのずれを直しました。
https://gyazo.com/fff57a8a7df8eeeb141a55ba282c43d2

お知らせページの実装

---

app/assets/stylesheets/_registration.scss
app/assets/stylesheets/logout.scss
app/assets/stylesheets/method_of_payment.scss
app/controllers/users_controller.rb
app/views/users/create_card.html.haml
app/views/users/method_of_payment.html.haml
config/routes.rb

クレジットカードの登録ページの実装をしました。
クレジットカード追加ボタンで登録ページに遷移できるようにしました。
年月がずれているが流用しているのであとで微調整します。
https://gyazo.com/e5eeb80eb0ade53adf9680c049d2adc7

クレジットカード登録ページの実装

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/exhibit_ok.scss
app/assets/stylesheets/exhibit_page.scss
app/views/items/exhibit_ok.html.haml
app/views/items/exhibit_page.html.haml
config/routes.rb

出品完了ページのマークアップ
出品したら、出品者に完了したことを伝えるため

出品完了ページマークアップ

---

app/assets/stylesheets/method_of_payment.scss
app/controllers/users_controller.rb
app/views/users/create_card.html.haml
app/views/users/my_card.html.haml
config/routes.rb

登録後に表示されるページの作成
ページのマークアップしました。
ページが遷移するようにしました。
https://gyazo.com/80884b801b465dff0ddc8a95f1f7e10f

登録後のページの実装

---

app/assets/stylesheets/_registration.scss
app/assets/stylesheets/method_of_payment.scss
app/assets/stylesheets/profile.scss
app/controllers/users_controller.rb
app/views/users/_mypage-side.html.haml
app/views/users/identification.html.haml
config/routes.rb

本人確認ページのマークアップをしました。
ページの遷移できるようにしました。
link_toを使いました。
微調整しました。
https://gyazo.com/924c1c73bc06cb3a2948f590718d2a43
https://gyazo.com/6b329d2e3cd8794ae0121bdf398bbff3

本人確認ページの実装

---

app/assets/stylesheets/profile.scss
app/views/users/edit.html.haml

アイコンが正しく表示されていなかったため
アイコンが正しく表示されるように微調整しました。
https://gyazo.com/09cce4668473be2324383b3caa729af4
https://gyazo.com/5b237cbbbbd95564916364369d8f7e62

プロフィールアイコンの微調整

---

app/assets/stylesheets/_registration.scss
app/views/signup/address_input.html.haml
app/views/signup/entry_start.html.haml
app/views/signup/howto_paiement.html.haml
app/views/signup/member_infomation.html.haml
app/views/signup/phone_number.html.haml
app/views/signup/sms_check.html.haml

- formタグをform_withに変更
- member_infomationのプルダウンにアイコンを表示
- howto_paiementのクレジットカード有効期限入力フォームをサイズ変更
- 次回ブランチでコントローラーの機能について実装開始予定
- railsの推奨仕様に合わせる為
https://gyazo.com/76d294de31b2588a883e2e977179a4cf
https://gyazo.com/cc105dd2861fcb7e64ddf47721408e05

ログイン送信フォーム手直し

---

app/views/items/_header.html.haml

ログイン時のヘッターとログアウト時のヘッターの表示を切り替えさせる（ビューのみ）
ログイン時はマイページ等に飛ぶようにするため
ログアウト時は新規登録、ログインができるようにするため

ログイン時とログアウト時の表示の分岐

---

app/models/category.rb
db/migrate/20191113112301_create_categories.rb
db/migrate/20191113114506_add_ancestry_to_category.rb
db/schema.rb
db/seeds.rb
spec/factories/categories.rb
spec/models/category_spec.rb

ancestryを用いてカテゴリーテーブルの作成
seedファイルにで初期DBに保存
テーブル一つで親、子、孫のカテゴリーを分けることができる。
配列を作りeachで取り出します。
seedファイルに記述しました。
記述が多かったので途中から省略しました。
https://gyazo.com/e8812b12572505d1a2c144d1a2b1ccdf
https://gyazo.com/5be2954ba84eb20913a10c952bec25eb

ancestry_categories

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_error_msg.scss
app/assets/stylesheets/_registration.scss
app/assets/stylesheets/application.scss
app/controllers/signup_controller.rb
app/models/user.rb
app/views/shared/_error-messages.html.haml
app/views/signup/member_infomation.html.haml
config/application.rb
config/initializers/active_record_extension.rb
config/locales/ja.yml

- エラーメッセージを場合毎に表示されるように実装
- 一度に表示されるエラーメッセージは１つまでになるように実装
- エラーメッセージは日本語で表示されるように実装
- 入力不備があった場合、ユーザーにわかりやすく明示する為。
- エラーメッセージが大量に生成されて煩わしくないようにする為。
https://gyazo.com/50d7c1aeee9690bed15cf43147b185fd
https://gyazo.com/22a206425ebdce2c6dbfd5120b0d8a09

サインアップのバリデーション

---

app/models/item.rb
app/models/user.rb
db/migrate/20191114042625_add_column_items.rb
db/schema.rb

Itemsテーブルにseller_idとbuyer_idのカラムを追加しました。
class_nameでアソシエーションしました。
ItemsテーブルとUsersテーブルの紐付け

Itemsテーブルとusersテーブルのアソシエーション 

---

app/controllers/signup_controller.rb
app/models/address.rb
app/models/prefecture.rb
app/views/signup/address_input.html.haml
db/migrate/20191115062245_add_prefecture_id_to_address.rb
db/schema.rb

- gem 'active_hash'を利用して都道府県のプルダウンを作成。
- それに伴いモデルのアソシエーションを設定
- DBにマジックナンバーで保存される事を確認
- ユーザーが登録時にプルダウンで選択できるようにする為。

アクティブハッシュの実装

---

app/assets/javascripts/categories.js
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/new.html.haml
db/schema.rb

#What
出品時のカテゴリー選択のバリデーション設定
#Why
親、子、孫カテゴリーを必ず登録してもらうため。

カテゴリーのバリデーション

---

app/controllers/cards_controller.rb
app/controllers/items_controller.rb
app/views/cards/show.html.haml
app/views/items/purchase_page.html.haml
config/routes.rb
db/schema.rb

- payjpの支払い機能を実装
- 商品の価格が商品毎に反映されるように記述
- 商品購入後に、購入完了ページへ遷移するよう実装
- ユーザーが商品を購入できるようにするため。
- ユーザーが商品代金を登録したクレジットカードを使って支払いできるようにするため。

商品が購入できるようにする機能の実装

---

app/assets/javascripts/images.js
app/assets/stylesheets/images_up.scss
app/views/items/new.html.haml

- 商品投稿ページの画像右下にある削除ボタンを機能するよう実装
- どの場所から削除しても削除およびその後の画像追加ができるように実装
- ユーザーが画像投稿後に不要な画像を削除できるようにする為
https://gyazo.com/b6e482477e27ab3904b3754e3809b549

投稿した画像の修正（削除機能）

---

app/assets/stylesheets/new_exhibit.scss
app/views/items/new.html.haml
app/views/layouts/_error_image.html.haml

・画像を投稿しないと出品できないようにバリデーションをかけた
・入力されているフィールドがある時バリデーション表示をなくした(修正)
・画像投稿なしでの出品をなくすため

画像のバリデーション追加＆データ保持

---

app/views/items/show.html.haml

商品詳細ページの編集
・カテゴリー表示追加
・未実装なビュー削除
商品の情報を正すため

カテゴリー追加＆不要なビュー

---

app/assets/stylesheets/items_show.scss
app/models/item.rb
app/views/items/new.html.haml

・画像のリサイズをしていたためsold out表示の修正
・enumの修正
sold out表示させないと購入者が勘違いしてしまうため

enum&SOULd画像サイズ
